- name: Initializing the custom variables used in branching  
  vars:
  set_fact:
    pre_trunk_statuses: {}
  tags:
    - pre-upgrade-hosts

- name: COLLECT BIG-IP trunks for "{{ inventory_hostname }}" using the FACTS module
  bigip_device_info:
    provider:
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
    gather_subset:
      - trunks
  register: trunks
  tags:
    - pre-upgrade-hosts

- name: Extracting the status of the trunks
  set_fact:
    pre_trunk_statuses: "{{ pre_trunk_statuses|default({}) | combine({item.name:item.media_status})  }}"
  loop: "{{ trunks.trunks }}"
  tags:
    - pre-upgrade-hosts


