
- name: Enable snmp traps
  bigip_snmp:
    agent_authentication_traps: enabled
    agent_status_traps: enabled
    device_warning_traps: enabled
    provider:
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
  when: standby_host|bool == true
  delegate_to: localhost
  tags:
    - pre-upgrade