- name: Fetch a qkview from the VCMP guest "{{ item }}"
  block:
    - name: Fetch qkview block
      bigip_qkview:
        dest: "{{ BACKUPS }}/{{ ITSM }}-{{ item }}.qkview"
        exclude_core: yes
        exclude: all
        provider:
          server: "{{ item }}"
          user: "{{ username }}"
          password: "{{ password }}"
          validate_certs: no
      delegate_to: localhost
  rescue:
    - name: fetching qkview failed, try manual and continue
      pause:
        seconds: 7200
  tags:
    - pre-upgrade



- name: Download a new UCS from the VCMP guest "{{ item }}"
  block:
    - name: Fetch UCS block
      bigip_ucs_fetch:
        src: "{{ ITSM }}_{{ item }}.ucs"
        dest: "{{ BACKUPS }}/{{ ITSM }}-{{ item }}.ucs"
        provider:
          server: "{{ item }}"
          user: "{{ username }}"
          password: "{{ password }}"
          validate_certs: no
      delegate_to: localhost
  rescue:
    - name: fetching ucs failed, try manual and continue 
      pause: 
        seconds: 7200
  tags:
    - pre-upgrade