- name: Make Directory on local system to store .ucs and .qkview files
  shell:  test -d "{{ BACKUPS }}" || mkdir "{{ BACKUPS }}" 
  tags:
    - pre-upgrade

- name: Fetch a qkview from the remote device
  block:
    - name: Fetch a qkview block 
      bigip_qkview:
        dest: "{{ BACKUPS }}/{{ ITSM }}-{{ inventory_hostname }}.qkview"
        exclude_core: yes
        provider:
          server: "{{ inventory_hostname }}"
          user: "{{ username }}"
          password: "{{ password }}"
          validate_certs: no
      delegate_to: localhost
  rescue:
    - name: fetching qkview failed, try manual and continue   
      pause:
        seconds: 7200    
  tags:
    - pre-upgrade

- name: Fetch a new UCS block
  block:
    - name: Fetch UCS
      bigip_ucs_fetch:
        src: "{{ ITSM }}_{{ inventory_hostname }}.ucs"
        dest: "{{ BACKUPS }}/{{ ITSM }}-{{ inventory_hostname }}.ucs"
        provider:
          server: "{{ inventory_hostname }}"
          user: "{{ username }}"
          password: "{{ password }}"
          validate_certs: no
      delegate_to: localhost
  rescue:
    - name: fetching ucs failed, try manual and continue   
      pause:
        seconds: 7200     
  tags:
    - pre-upgrade