# - name: Initializing the custom variables used in branching  
#   vars:
#   set_fact:
#     pool_statuses: {}
#   tags:
#     - post-upgrade-guests



# - name: COLLECT BIG-IP ltm Pools for "{{ item }}" using the FACTS module
#   bigip_device_info:
#     provider:
#       server: "{{ item }}"
#       user: "{{ username }}"
#       password: "{{ password }}"
#       validate_certs: no
#     gather_subset:
#       - ltm-pools
#   register: pools
#   tags:
#     - post-upgrade-guests

# - name: Extracting the status of the pools
#   set_fact:
#     pool_statuses: "{{ pool_statuses|default({}) | combine({item.name:item.availability_status})  }}"
#   loop: "{{ pools.ltm_pools }}"
#   tags:
#     - post-upgrade-guests


# - name: Copy output to file
#   copy:
#     content: "{{ pool_statuses }}"
#     dest: "{{ TMP }}/{{ item }}.json"
#   tags:
#     - post-upgrade-guests



####

- name: Getting the status of pools from "{{ item }}"
  bigip_command:
    commands: tmsh show ltm pool recursive field-fmt members 
    provider: 
      server: "{{ item }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
  delegate_to: localhost
  register: tmshPoolStatus
  tags:
    - post-upgrade-guests

- name: List the status
  debug:
    msg: "{{ tmshPoolStatus }}"
  tags:
    - post-upgrade-guests

- name: Copy output to file
  copy:
    content: "{{ tmshPoolStatus.stdout }}"
    dest: "{{ TMP }}/{{ item }}.json"
  delegate_to: localhost
  tags:
    - post-upgrade-guests

- name: Run the python script to parse the status of the pools
  shell: python3 formatTmsh.py "{{ item }}"
  args:
    chdir: "{{ SCRIPTS }}"    
  tags:
    - post-upgrade-guests