
- name: Set random high volume when single slot
  set_fact:
    volume: "HD1.5"
  when: volumes | length == 0 
  tags:
    - upgrade-hosts

- name: Install software on VCMP host "{{ inventory_hostname }}"
  bigip_software_install:
    image: "{{ ISO_IMAGE }}"
    volume: "{{ volume }}"
    state: installed
    provider:
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      server_port: 443
      validate_certs: no
  delegate_to: localhost
  tags:
    - upgrade-hosts